name: BasicEssentials
version: '${project.version}'
main: basicessentials.basicessentials.BasicEssentials
api-version: 1.17
authors: [ Fluid4321 ]
description: A lightweight version of essentials featuring command shorterners, permissions, messaging systems and more.
website: https://github.com/wb51182/
commands:
  gamemode:
  fly:
  heal:
  kill:
  afk:
  fun:
  message:
  reply:
  setspawn:
  spawn:
  rank:
    aliases: ranks
  setrank:
  rankinfo: